### ISSUE TITLE
legacy confusion

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-replicate#1]
The README says this is legacy, but doesn't point at what supercedes it (presumably `ssb-ebt`).

Further, `ssb-server` has both `ssb-replicate` and `ssb-ebt` installed. Does it use both. If it does I think we should change the legacy note to be more descriptive.

I also notice in `ssb-ebt` that it's messing with `ssb-replicate` config, and that `ssb-replicate` seems to be listening to see if it's needed and being a fallback? I couldn't follow the logic or where the emitted messages are going. I basically just need to know : 
- do I need both
- do they need to be installed (`.use()`) in a particular order
- is this module deprecated 
  - .i.e. are we going to remove it ultimately (maybe leave a note about that)

**Comment by dominictarr** [comment]
okay so currently, you do need ssb-replicate to be installed first.
ssb replicate provides `replicate.request(id, toReplicate)` which ssb-ebt hooks into (overrides)

hmm... maybe instead of calling replicate.request we could emit a local event `sbot.emit('replicate:request', id, toReplicate)` and then any replication plugins could listen for that.
hmm, this approach would also work for ssb-gossip, which needs to have a way to receive peers to connect to. @staltz is rewriting a new gossip manager... so we should use a consistent pattern, I think this would work for him too. (we could also use something different, this is just the first thing that came to mind)

**Comment by christianbundy** [comment]
> okay so currently, you do need ssb-replicate to be installed first.

!!!

I usually sort my `.use()` chain alphabetically and it's always given me replication problems, which *totally makes sense now*. Thanks! Aside: are there any other secret-stack modules that need to be loaded before others? Right now I'm loading ssb-db and ssb-ebt [before all of the others](https://github.com/fraction/flotilla/blob/90709010bf4010770a1c025754d7df759e2e8582/index.js#L3-L4), but I wouldn't be surprised if other things are broken too.

**Comment by staltz** [comment]
> Aside: are there any other secret-stack modules that need to be loaded before others?

Oh certainly. This is a common thing.

**Comment by dominictarr** [comment]
> I usually sort my .use() chain alphabetically and it's always given me replication problems

uh that's not gonna work for cases where one thing depends on the other. you should load in topographical order... more core first, less core later. how then what, or "opinions last"

**Comment by christianbundy** [comment]
Could someone point me to the documentation about which plugins need to be loaded before others? I've figured out that ssb-db and ssb-replicate need to be loaded before the others, but that's not obvious to people who are trying out our code. I'd expect that if a plugin relies on another then it should be failing loudly and clearly on startup.

**Comment by dominictarr** [comment]
oh I don't think that documentation exists but it certainly should!
> I'd expect that if a plugin relies on another then it should be failing loudly and clearly on startup.
Agree. Sometimes this would happen just because of the type error... maybe not helpful though.
Because of the way this has evolved this hasn't happened as a policy though

**Comment by christianbundy** [comment]
One way to find out...

I'm going to try [shuffling my secret-stack plugins](https://github.com/fraction/flotilla/blob/shuffle/index.js) to try to find some bugs. :crossed_fingers:

**Comment by dominictarr** [comment]
> I usually sort my .use() chain alphabetically and it's always given me ... problems,

curiously: I'd never arrange deps alphabetically. If there are lots I tend to sort them in "coreness" for example, group node core modules, files inside this package, generic modules, and specific application (eg, ssb modules) more important things first etc. I think this comes down to me processing code more visually and less linguistically. the nice thing about alphabetical order is that it's canonical, but the nice thing about group by relation to this module is that you convey more meaning

**Comment by staltz** [comment]
Back to the initial question of this issue, we could consider reimplementing ssb-ebt so that it *includes* ssb-replicate inside it, **or** reimplements ssb-replicate primitives (the ones that we want to keep, dropping the ones that we don't need), then ssb-ebt can run an init-level check whether ssb-replicate exists, and if it exists, throw an error. This would make it clear that you either include ssb-replicate xor ssb-ebt, not both.

**Comment by dominictarr** [comment]
> This would make it clear that you either include `ssb-replicate` xor `ssb-ebt`, not both.

hmm, both are needed because then you can communicate with ebt peers, and legacy peers.
but it's also possible to just have ebt. (unfortunately no other than the js implementation supports ebt yet)

**Comment by staltz** [comment]
Yes Dominic, I meant that if `ssb-ebt` (as a module, not as a protocol) includes both EBT and Legacy (as protocols), then the developer installing the plugins doesn't have to remember to include both `ssb-ebt` and `ssb-replicate`.

If we want ssb-ebt to only support the EBT protocol, we could pass that in as an argument option. We'd likely keep this option unused for a long time until many peers migrate to EBT-only.
