### ISSUE TITLE
Error replicating with

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-replicate#12]
In Oasis I'm seeing lots of logs like:

```
Error replicating with @G20wv2IZkB7BA/LKe7WMuByop3++J0u9+Y32OoEVOj8=.ed25519:
```

This is done here:

https://github.com/ssbc/ssb-replicate/blob/28d763ce2da79b870547b247eecff0fe56baf17c/legacy.js#L286-L289

Instead, I can `console.error(err)` and see the underlying problem:

```js
{
  name: 'Error',
  message: `bad request: ssb/message: not a feed ref: feedRef: couldn't parse "@S9lG7keeOfIAepU1LRD9XUDtuesbejRC2+3/FRaGZ3s=.sha256": ssb: Invalid Ref Algo`,
  stack: ''
}
```

Are we calling `createHistoryStream("@abc.sha256")` for some reason? Or are they?

cc: @cryptix (not urgent, just some random stdout I'm looking at)

**Comment by cryptix** [comment]
Yup, for some reason the JS stack doesn’t check if follow messages are for valid feed references and some people accidentally made them with SHA suffixes. What ever that is supposed to mean, I think it’s good to return an error for references that are not understood instead of quietly returning an empty stream.
